procedure OnPlanRoadDigged(aPlayer, X, Y: integer);
begin
	Actions.ShowMsg(0, IntToStr(aPlayer) + ' / ' + IntToStr(X) + ' / ' + IntToStr(Y) + ' / road');
end;

procedure OnPlanWinefieldDigged(aPlayer, X, Y: integer);
begin
	Actions.ShowMsg(0, IntToStr(aPlayer) + ' / ' + IntToStr(X) + ' / ' + IntToStr(Y) + ' / winefield');
end;

procedure OnHousePlanDigged(aHouse:integer);
begin
	Actions.ShowMsg(0, IntToStr(aHouse) + ' / house');
end;